name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js v18.*
      uses: actions/setup-node@v4
      with:
        node-version: 18.*.*
        cache: 'npm'
    - name: Install Dependencies
      run: npm install
    - name: Start application
      run: npm start
    - name: Run Integration Tests
      run: npm test
