name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js v18.*
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install Dependencies
      run: npm install
    - name: Start application
      run: npm start &
    - name: Run Integration Tests
      run: npm test

  deploy:
   if: github.ref == 'refs/heads/main' 
   runs-on: ubuntu-latest
   needs: unit_tests
   steps:
    - name: Deploy to production
      uses: JorgeLNJunior/render-deploy@v1.4.5
      with:
          service_id: ${{ secrets.RENDER_SRV_TOKEN }}
          api_key: ${{ secrets.RENDER_TOKEN }}
          wait_deploy: true
